### ISSUE TITLE
Wrong chapter numbers when toctrees located in different .rst files

### ISSUE THREAD

**Issue by guyikcgg** [executablebooks/sphinx-multitoc-numbering#14]
**Describe the bug**

I'm using (numbered) `toctree`s in multiple files. I include these files in the toplevel (unumbered) `toctree`. When I do this, chapter numbers are not properly ordered (the first chapter to be numbered is not in part 1).

**To Reproduce**

Assume the following project structure:

```
index.rst
unumbered_chapter.rst
part1/index.rst
part1/chapter1.rst
part1/chapter2.rst
part2/index.rst
part2/chapter3.rst
part3/index.rst
part3/chapter4.rst
```

Contents of `index.rst` are:
```
.. toctree::
    :maxdepth: 2

    unumbered_chapter
    part1/index
    part2/index
    part3/index
```

Contents of `part1/index.rst` are:
```
.. toctree::
    :numbered:

    chapter1
    chapter2
```

Contents of `part2/index.rst` and `part3/index.rst` are analogous.

In my case, I get the toplevel TOC messed up, like:
```
* Part 1
  3. Chapter 1
  4. Chapter 2
* Part 2
  1. Chapter 3
* Part 3
  2. Chapter 4
```

Note: the problem does not always happen, but it does in most of the `sphinx-build`s.

**Expected behavior**

The output should be:
```
* Part 1
  1. Chapter 1
  2. Chapter 2
* Part 2
  3. Chapter 3
* Part 3
  4. Chapter 4
```

**Environment**

- Running Sphinx v3.2.1
- Python Version 3.5.2:
- Not using `jupyter-book`
- Operating System: Linux rti-10636 4.15.0-118-generic #119~16.04.1-Ubuntu SMP Tue Sep 8 14:54:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

N/A

**Comment by AakashGfude** [comment]
Thank you @guyikcgg for the issue. Interesting. I have not tried this setup before for this extension, of having numbered part toctrees inside a parent toctree. I suspect sphinx is traversing the numbered toctrees in a different order here. 
I will create a similar setup and give this a spin, or if you have it hosted in a repo, then a link to that will be helpful as well :)

**Comment by guyikcgg** [comment]
@AakashGfude, thanks for the quick reply! I have created a reproducer under https://github.com/guyikcgg/sphinx-multitoc-numbering-issue14

Please take a look at it and let me know if you need further input :slightly_smiling_face:

**Comment by AakashGfude** [comment]
That's very helpful. Cheers. Will have a look at it in a day or two.
