### ISSUE TITLE
Outdated PyPI version of the package

### ISSUE THREAD

**Issue by So-Cool** [executablebooks/sphinx-multitoc-numbering#18]
**Describe the bug**

The [PyPI repository](https://pypi.org/project/sphinx-multitoc-numbering/#history) holds an outdated (0.1.1) version of the `sphinx-multitoc-numbering` package.

**To Reproduce**

`pip install sphinx-multitoc-numbering` pulls the outdated **0.1.1** version of the package.

**Expected behavior**

`pip install sphinx-multitoc-numbering` should pull the latest **0.1.2** version of the package.

**Environment**

N/A

**Additional context**

N/A

**Comment by AakashGfude** [comment]
Hello @So-Cool , Thanks for notifying us of this error. Sorry, for getting at it a bit late. 
It should be working fine now.
