### ISSUE TITLE
Update name to sphinx-multitoc-numbering

### ISSUE THREAD

**Issue by mmcky** [executablebooks/sphinx-multitoc-numbering#4]
As discussed with @AakashGfude a more generic / descriptive name for this `sphinx-multitoc-numbering` as it fixes numbering in the context of multiple `toctree` in the `sphinx ast`. 

- [ ] @AakashGfude if not there already we should also attribute this to its source (with a link to the discussion it came from in `sphinx-doc` organisation) in the docs and changes made to it.

**Comment by AakashGfude** [comment]
@mmcky great idea. Will add these things to the doc

**Comment by AakashGfude** [comment]
@mmcky have added inspiration to the docs https://github.com/executablebooks/sphinx-multitoc-numbering/blob/master/docs/source/index.md#inspiration

**Comment by AakashGfude** [comment]
@mmcky closing this issue as updated inspiration section.
