### ISSUE TITLE
[TEST] Test with lecture-python-programming.myst

### ISSUE THREAD

**Issue by mmcky** [executablebooks/sphinx-multitoc-numbering#6]
**Describe the bug**

We should test with the `quantecon` migration of [lecture-python-programming.myst](https://github.com/QuantEcon/lecture-python-programming.myst) to see how it work on a real world project. 

@AakashGfude would you mind to test and add an update below. 

**Test Report:**

TBD

**Comment by AakashGfude** [comment]
@mmcky  I believe it is working with `lecture-python-programming.myst` without any issues?
